Sponsorship invariant
stellar/stellar-core pull request #2672
Opened 2020-08-13 18:55 UTC by jonjove

# Description
Update the invariants subsystem for sponsorships.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

2020-08-14 17:02 UTC, sisuresh commented on src/main/ApplicationImpl.cpp
> +}
Nit: Looks like you added a newline?

2020-09-11 21:50 UTC, sisuresh commented
@jonjove Should we include some test cases for `SponsorshipCountIsValid`? I noticed that we didn't have any test cases for `LedgerEntryIsValid` and it got me thinking. I think we should have a test case to at least verify that each invariant is being run.

2020-09-11 21:58 UTC, jonjove commented
Yes, the reason I've been delaying on merging this is that I haven't gotten around to writing tests. But I think it's a good principle to test that:
a) every invariant is at least getting run (as you point out)
b) it handles some common cases and non-cases correctly

Hopefully I'll get the tests written next week.

2020-09-24 18:08 UTC, MonsieurNicolas requested changes

2020-09-29 16:43 UTC, jonjove commented on src/invariant/LedgerEntryIsValid.cpp
> +    if (ae.ext.v() == 1 && ae.ext.v1().ext.v() == 2)
Fixed.

2020-09-29 16:43 UTC, jonjove commented on src/ledger/test/LedgerTestUtils.cpp
> +        c.claimants.resize(1);
Added a comment.

2020-09-29 16:43 UTC, jonjove commented on src/invariant/SponsorshipCountIsValid.cpp
> +// Copyright 2020 Stellar Development Foundation and contributors. Licensed
Done.

2020-09-29 16:43 UTC, jonjove commented on src/invariant/test/SponsorshipCountIsValidTests.cpp
> +// Copyright 2020 Stellar Development Foundation and contributors. Licensed
Done.

2020-10-09 22:07 UTC, MonsieurNicolas commented
r+ 142fc5914ede400c4517a739aef761a89e12fec7

2020-10-09 23:30 UTC, merged