Remove the <= and bool operators from the BitSet class
stellar/stellar-core pull request #2807
Opened 2020-11-17 20:14 UTC by hidenori-shinohara

# Description

Resolves https://github.com/stellar/stellar-core/issues/2800

This PR removes the `<=` and `bool` operators from the `BitSet` class.

* The issue https://github.com/stellar/stellar-core/issues/2800 has some discussion on why we might consider removing `<=`.
* If we remove the `<=` operator but keep the `bool` operator, then `bitset1 <= bitset2` still compiles and runs (I think C++ implicitly converts each bitset into a boolean value and compare.) I felt that that might create some more confusion in the future (also the `bool` operator is defined to be `nonempty`, which may not be obvious to some people), so I decided that we might consider removing it, also.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [x] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

2020-11-21 01:08 UTC, MonsieurNicolas requested changes
minor nit

2020-11-21 01:08 UTC, MonsieurNicolas commented on src/herder/QuorumIntersectionCheckerImpl.cpp
> +        if (!(mCommitted.isSubsetEq(extensionQuorum)))
remove extra `()`

2020-11-23 18:47 UTC, hidenori-shinohara commented on src/herder/QuorumIntersectionCheckerImpl.cpp
> +        if (!(mCommitted.isSubsetEq(extensionQuorum)))
Fixed!

2020-11-24 22:31 UTC, MonsieurNicolas commented
r+ c487f50f612244d8f5d3a07e656f8409a19f8fd3

2020-11-24 22:50 UTC, merged