Use a randomized hasher in unordered sets/maps
stellar/stellar-core pull request #2812
Opened 2020-11-20 02:51 UTC by MonsieurNicolas

# Description

Resolves #2809

The only real change is the first commit, rest is search/replace.

PR for now has this always enabled.
We could enable this on builds with `--enable-extrachecks` enabled, but having this always on gives better confidence that mitigations are in place in production environments.

2020-11-20 19:51 UTC, MonsieurNicolas commented
Looking at the failure of *one* of the test cases (clang only), it seems, if I am not mistaken that this approach is actually not viable.

I started to read https://en.cppreference.com/w/cpp/container/unordered_set/operator_cmp and noticed the wording
> The behavior is also undefined if hash_function() and key_eq() do (until C++20)key_eq() does (since C++20) not have the same behavior on lhs and rhs or if operator== for Key is not a refinement of the partition into equivalent-key groups introduced by key_eq() (that is, if two elements that compare equal using operator== fall into different partitions)

the way I read this, it seems they may be using the hash function associated with `this` on *both* containers.

Even if this was not the case, we'd still need to fix the wrappers, as right now I am doing something like
```c++
template <class T, class Hasher = std::hash<T>> class RandHasher
{
    size_t mMixer{0};

  public:
    RandHasher()
    {
        mMixer =
            stellar::rand_uniform<size_t>(std::numeric_limits<size_t>::min(),
                                          std::numeric_limits<size_t>::max());
    }
    size_t
    operator()(T const& t) const
    {
        return Hasher()(t) ^ mMixer;
    }
};
```

which is unsafe as it does not satisfy the "stability requirement" for [std::hash](https://en.cppreference.com/w/cpp/utility/hash):
> For two parameters k1 and k2 that are equal, `std::hash<Key>()(k1) == std::hash<Key>()(k2)`

(note the use of default constructor here)

We could *maybe* ignore this and enforce that there is no way to "default construct" an instance of `RandHash` but I suspect we'd be potentially fighting with more bugs: we'd have to enforce constructing std::unordered_set/map with an actual hash object (so explicitly define all constructors).

2020-11-20 20:27 UTC, MonsieurNicolas commented
I am reducing the scope of that PR that use a seed per set/map type instead of per instance, not as good but this is definitely something we can include all the time

2020-11-25 19:39 UTC, graydon requested changes
Looks ok.

2020-11-25 19:39 UTC, graydon commented on Builds/VisualStudio/stellar-core.vcxproj
> +    <ClCompile Include="Source.cpp" />
Is this intentional?

2020-11-25 19:39 UTC, graydon commented on Builds/VisualStudio/stellar-core.vcxproj.filters
> +    <ClCompile Include="Source.cpp">
Likewise this? Seems a typo

2020-11-25 19:39 UTC, graydon commented on src/util/RandHasher.h
> +        static size_t mixer =
I'm not sure it's ok to be using a static local for this -- you could race with another thread on initialization and get a hashtable that uses a half-written `mixer` value or a `mixer` that's initialized twice.

2020-11-25 19:54 UTC, graydon approved these changes

2020-11-25 19:58 UTC, graydon commented
r+ 91fa519

2020-11-25 20:50 UTC, merged