Improve naming of externalize metrics
stellar/stellar-core pull request #2941
Opened 2021-03-02 18:02 UTC by marta-lokhova

Resolves #2864

2021-03-09 02:47 UTC, MonsieurNicolas requested changes

2021-03-09 02:47 UTC, MonsieurNicolas commented on docs/metrics.md
> +scp.timing.self-to-first-externalize-lag | timer     | delay between first externalize message and local node externalizing
`self-to-` sounds like self is *before*. So maybe this should be `self-from-first-externalize-lag` ?

2021-03-09 02:47 UTC, MonsieurNicolas commented on docs/metrics.md
> +scp.timing.rest-to-self-externalize-lag  | timer     | delay between local node externalizing and later externalize messages from other nodes
this one also is not super clear. Maybe `self-to-other-externalize-lag` *or* `other-from-self-externalize-lag`

2021-03-10 18:12 UTC, MonsieurNicolas commented on docs/metrics.md
> +scp.timing.self-to-first-externalize-lag | timer     | delay between first externalize message and local node externalizing
actually using the "from" variant is bad, we should just use "to" so in this case `first-to-self-externalize-lag`

2021-03-10 18:13 UTC, MonsieurNicolas commented on docs/metrics.md
> +scp.timing.rest-to-self-externalize-lag  | timer     | delay between local node externalizing and later externalize messages from other nodes
same than earlier "to" reads more naturally I think

2021-03-10 19:08 UTC, marta-lokhova commented
updated

2021-03-13 01:14 UTC, MonsieurNicolas commented
r+ 5636e8d1d135985b65b1d1ea0633f89dee7a7b38

2021-03-13 01:45 UTC, merged