More CAP-0038 tests
stellar/stellar-core pull request #3209
Opened 2021-09-13 23:38 UTC by sisuresh

# Description

# Checklist
- [ ] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [ ] Rebased on top of master (no merge commits)
- [ ] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [ ] Compiles
- [ ] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

2021-09-16 16:04 UTC, jonjove reviewed
A couple of minor comments but looks pretty good.

2021-09-16 16:04 UTC, jonjove commented on src/transactions/test/SetTrustLineFlagsTests.cpp
> +                    // root is no longer sposooring the trustline, but it is
Nitpick: typo "sposooring" -> "sponsoring"

2021-09-16 22:02 UTC, sisuresh commented on src/transactions/test/SetTrustLineFlagsTests.cpp
> +        });
`revoke from multiple pools` should cover that case.

2021-09-16 23:52 UTC, sisuresh commented on src/transactions/test/SetTrustLineFlagsTests.cpp
> +                    // root is no longer sposooring the trustline, but it is
fixed

2021-09-16 23:52 UTC, sisuresh commented on src/transactions/test/SponsorshipTestUtils.cpp
> +            tooManySponsoring(reservesForSuccesfulOp + 1);
Added a comment

2021-09-16 23:52 UTC, sisuresh commented on src/transactions/test/SetTrustLineFlagsTests.cpp
> +                SECTION("same reserve - issuer sandwich on revoke - success")
Done

2021-09-17 14:45 UTC, jonjove commented on src/transactions/test/SetTrustLineFlagsTests.cpp
> +        });
Because you force rebased, I don't know what I was commenting on before. Can you point me to the code where this comment was before?

2021-09-17 14:49 UTC, jonjove commented on src/transactions/test/SetTrustLineFlagsTests.cpp
> +        });
But whatever I was commenting on, I meant testing that specific case in the context of 3 claimable balances not just producing 3 in general.

2021-09-22 17:10 UTC, MonsieurNicolas requested changes
Looks pretty extensive!
Only thing I noted is that you included a code coverage file in one of the commits and we can merge.
It also seems to me that this approach to testing is probably not sustainable as it's high effort (but that's something we should discuss when we're done with this round of protocol changes).

2021-09-22 17:57 UTC, sisuresh commented on src/transactions/test/SetTrustLineFlagsTests.cpp
> +                auto submitRevokeInSandwich =
Fixed

2021-09-23 03:54 UTC, MonsieurNicolas commented
r+ f6e898ceb72b469f7d6ff14fa5cd1a9c1457da68

2021-09-23 04:25 UTC, merged