Check for DB file existence in captive core
stellar/stellar-core pull request #3268
Opened 2021-11-12 19:37 UTC by marta-lokhova

Resolves #3248

2021-11-13 02:35 UTC, MonsieurNicolas requested changes

2021-11-13 02:35 UTC, MonsieurNicolas commented on src/main/ApplicationUtils.cpp
> +    return fmt::format(FMT_STRING("sqlite3://{}"), minimalDbPath(cfg));
note that if you return a path, you'll have to use `generic_string()` here as you want `/` on all platforms

2021-11-15 18:57 UTC, marta-lokhova commented on src/main/ApplicationUtils.cpp
> +    return fmt::format(FMT_STRING("{}/{}"), cfg.BUCKET_DIR_PATH,
good idea, updated

2021-11-16 23:13 UTC, MonsieurNicolas commented
r+ cc0ac9480b70afcc72139e59e5eb3b54a2b2cbdc

2021-11-16 23:35 UTC, merged