Delete temporary files while catching up
stellar/stellar-core pull request #3306
Opened 2022-01-07 23:41 UTC by graydon

This limits temporary disk space used during catchup by deleting tx and ledger files as soon as we're done with them. It will still store MAX_CONCURRENT_SUBPROCESSES (default 16) worth of tx files at any time -- and since it verifies the entire header chain before starting it will download that all at once -- but that's comparatively small.

2022-01-07 23:42 UTC, graydon commented
cc @paulbellamy

2022-01-10 16:20 UTC, marta-lokhova requested changes
Thanks for fixing this! I think the file deletion logic belongs in `DownloadApplyTxsWork` though, since this is where we create a sequence of work "download + apply" for each checkpoint. So you can just add a new work, "delete", to the sequence (note that we can use `WorkWithCallback` for this)

2022-01-12 01:34 UTC, graydon commented
@marta-lokhova updated! I'll be out the next few days so if you want to make any further tweaks, go ahead!

2022-01-12 09:54 UTC, paulbellamy commented
With this, the reingestion that was using 25GB+ now levels off at ~5.8GB.

2022-01-12 22:15 UTC, MonsieurNicolas commented
r+ aa6f7c164ba92fcc0a2b8268d03154030c81f8e0

2022-01-12 22:40 UTC, merged