Implement the InvokeHostFunctionOp part of CAP-52
stellar/stellar-core pull request #3450
Opened 2022-06-14 22:48 UTC by jonjove

# Description

Implements the `InvokeHostFunctionOp` part of CAP-52, but does not include the host functions.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

2022-06-15 04:55 UTC, graydon requested changes
Looks generally good! A few minor touchups.

2022-06-15 15:29 UTC, leighmcculloch commented on src/protocol-next/xdr/Stellar-transaction.x
> +    void;
cc @paulbellamy

2022-06-15 15:47 UTC, jonjove commented on src/transactions/InvokeHostFunctionOpFrame.cpp
> +    rust::Vec<XDRBuf> xdrBufs;
Done.

2022-06-15 15:47 UTC, jonjove commented on src/transactions/InvokeHostFunctionOpFrame.cpp
> +        // TODO(jonjove): Invalid
Yes, thanks for noticing. The XDR was missing when I originally wrote this and I forgot to go back. Fixed!

2022-06-15 15:57 UTC, jayz22 commented on src/protocol-next/xdr/Stellar-transaction.x
> +    void;
Probably not directly related to this but just to mention, as part of error-handling there is likely going to be a non-void return value in the INVOKE_HOST_FUNCTION_TRAPPED case, that either contains an SCVal or just an SCStatus containing the error code, so the user can get diagnostic information out.

2022-06-15 16:25 UTC, sisuresh commented on src/transactions/OperationFrame.cpp
> +#include "transactions/InvokeHostFunctionOpFrame.h"
Not necessary since InvokeHostFunctionOpFrame.h itself is wrapped in an ifdef, but should we add the conditional guard here as well to be thorough?

2022-06-15 16:58 UTC, jonjove commented on src/transactions/InvokeHostFunctionOpFrame.cpp
> +InvokeHostFunctionOpFrame::InvokeHostFunctionOpFrame(Operation const& op,
Good catch, fixed.

2022-06-16 04:55 UTC, graydon commented on src/protocol-next/xdr/Stellar-transaction.x
> +    void;
I buy this argument for now -- I think we might change our minds and come back and add a return value at some future point but it's plausible not to want one and I think we have enough other fish to fry that this shouldn't block.

2022-06-16 04:57 UTC, graydon approved these changes

2022-06-16 04:59 UTC, graydon commented
LGTM -- I leave the landing sequence to you, I think you might need to merge the other 2 first and then bump the Cargo.toml here to point to the post-merge revision ID of the env crate.

2022-06-17 15:54 UTC, sisuresh commented
r+ a68b53eb524c2bc20c628324eed578a598c23245

2022-06-17 19:29 UTC, sisuresh commented
r+ b1d22f7c98a653f25baad2475540edcacbf4e325

2022-06-17 21:00 UTC, merged