Loadgen startup fix
stellar/stellar-core pull request #4087
Opened 2023-12-12 18:02 UTC by marta-lokhova

Resolves https://github.com/stellar/stellar-core/issues/4071

2023-12-14 23:51 UTC, SirTyson requested changes
Looks good! I think we can clean up the start function a little more though.

2023-12-14 23:51 UTC, SirTyson commented on src/simulation/LoadGenerator.cpp
> +    if (!mStarted && cfg.isSoroban())
`start` should be a no-op except on the first invocation, so why not add `if (mStarted) return;` at the beginning and get rid of the checks in the individual ifs. Currently the only functions that get called multiple times in `start` are `createRootAccount` and `updateMinBalance`. If we need to call those periodically they probably don't belong in `start` (but I don't think we do).

2023-12-14 23:51 UTC, SirTyson commented on src/simulation/LoadGenerator.cpp
> +    createRootAccount();
Now that we have a single start function, we should change `if (!mRoot)` to `releaseAssert(!mRoot)` in `createRootAccount()`.

2023-12-14 23:51 UTC, SirTyson commented on src/simulation/LoadGenerator.cpp
> +    if (!mStartTime)
I think we should change this to `releaseAssert(!mStartTime)` (assuming you implement my other comment where we exit early in `start()`).

2023-12-20 05:08 UTC, marta-lokhova commented
@SirTyson added your suggestions, so this should be ready now

2023-12-20 17:21 UTC, SirTyson approved these changes
LGTM, one small nit.

2023-12-20 17:21 UTC, SirTyson commented on src/simulation/LoadGenerator.cpp
> +        {
Nit: Extra brackets

2023-12-20 17:46 UTC, marta-lokhova commented on src/simulation/LoadGenerator.cpp
> +        {
oops, fixed

2023-12-20 17:49 UTC, sisuresh commented
r+ fce809d6f1121539cb29b39580b05f55d56c21b2

2023-12-20 19:00 UTC, merged