Strkey update
stellar/stellar-core pull request #4195
Opened 2024-02-15 05:35 UTC by graydon

This just makes some parts of core that were not previously up to date wrt. new strkey forms (specifically SCAddress-related) a bit more up to date.

Resolves #4184

2024-02-15 22:00 UTC, MonsieurNicolas requested changes

2024-02-15 23:06 UTC, graydon commented on src/crypto/SecretKey.cpp
> +        s << "  STRKEY_MUXED_ACCOUNT_ED25519: "
ok .. should I print anything here? I don't really understand muxed accounts. is it meaningful for a user to ask to `convert-id` for a hex value that's a muxed account?

2024-02-15 23:06 UTC, graydon commented on src/crypto/StrKey.h
> +    STRKEY_CONTRACT = 2,                // 'S'
fixed

2024-02-21 04:55 UTC, MonsieurNicolas commented on src/crypto/SecretKey.cpp
> +        s << "  STRKEY_MUXED_ACCOUNT_ED25519: "
I don't think so: muxed accounts don't actually exist at core's layer.
Maybe there is something that makes sense for them here though, but I would not block this PR on it, and instead not deal with them at all in this PR

2024-02-21 19:35 UTC, graydon commented on src/crypto/SecretKey.cpp
> +        s << "  STRKEY_MUXED_ACCOUNT_ED25519: "
Ok, I just added a runtime throw in that case instead.

2024-02-21 20:14 UTC, MonsieurNicolas commented
r+ 3bdba17edaba4d1045ccc846d0f2c53d3df1f5b2

2024-02-22 01:11 UTC, graydon commented
r+ ff88f97

2024-02-22 02:20 UTC, merged