BucketListDB enabled by default
stellar/stellar-core pull request #4277
Opened 2024-04-08 22:10 UTC by SirTyson

# Description

Resolves #4202

This change defaults BucketListDB to enabled. The optional `EXPERIMENTAL_BUCKETLIST_DB` has been changed to the required flag `DEPRECATED_SQL_LEDGER_STATE`. If this flag is not set, core will fail to start. When BucketListDB is enabled for the first time, many SQL tables are dropped and can only be recovered by replaying many transactions. Crashing if this flag is not explicitly defined protects operators from accidentally dropping these tables when upgrading.

I'm not set on the name `DEPRECATED_SQL_LEDGER_STATE`, but I wanted to include "deprecated" in the name to discourage using SQL for ledger state as much as possible.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

2024-04-26 22:51 UTC, SirTyson commented
After some discussion (https://github.com/stellar/stellar-core/issues/4202), we are going to keep the experimental flags for the 21.0 release to not break compatibility with Horizon. We still want to require that some BucketListDB related flag is set on startup, so operators must either use the new `DEPRECATED_SQL_LEDGER_STATE` flag or the previous experimental flag. Additionally, we will support all the old `EXPERIMENTAL_` parameters in addition to their new counterparts that have dropped the "EXPERIMENTAL" from the parameter name.

2024-05-01 19:02 UTC, marta-lokhova requested changes

2024-05-01 19:25 UTC, SirTyson commented on src/main/Config.h
> +    bool DEPRECATED_SQL_LEDGER_STATE;
We still support it in the config file itself, but it's just been renamed in the config class to a single name. See `src/main/Config.cpp:1084`.

2024-05-02 17:43 UTC, graydon commented
r+ a1de765

2024-05-02 18:55 UTC, merged