Address pull mode tech debt
stellar/stellar-core pull request #4294
Opened 2024-04-23 17:31 UTC by marta-lokhova

2024-04-23 23:20 UTC, bboston7 approved these changes

2024-04-24 16:22 UTC, graydon requested changes
Generally positive save a single issue: the names are a bit unclear / general / confusing. Perhaps TxPullMode -> TxAdverts, and TxFloodManager -> TxDemands?

2024-04-24 16:50 UTC, marta-lokhova commented on src/overlay/TxPullMode.h
> +    // Queue up transaction hashes to retry demanding
Done!

2024-04-24 18:30 UTC, marta-lokhova commented
> Generally positive save a single issue: the names are a bit unclear / general / confusing. Perhaps TxPullMode -> TxAdverts, and TxFloodManager -> TxDemands?

Done.

2024-04-24 19:21 UTC, graydon commented
r+ b1bb9e4

2024-04-24 20:05 UTC, merged