ApplyBucketWork at per-bucket level
stellar/stellar-core pull request #4314
Opened 2024-05-14 17:30 UTC by ThomasBrady

# Description

Resolves #X

# Checklist
- [ ] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [ ] Rebased on top of master (no merge commits)
- [ ] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [ ] Compiles
- [ ] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

2024-05-14 17:36 UTC, ThomasBrady commented on src/catchup/ApplyBucketsWork.cpp
> +            advance(isCurr ? "curr" : "snap", applicator);
I assume we still want log messages to print `snap` / `curr` to show more granular progress? If not I can remove this logic as well

2024-05-15 21:35 UTC, SirTyson requested changes
Currently, this doesn't work because `advance` is not being called properly. The way the work classes are designed, we do long running jobs in chunks to not hog resources. The expectation is that `doWork()` will be called periodically, do a little work, then return quickly.

`BucketApplicator` assumes this interface. If you look at `BucketApplicator::advance`, you'll see that it only applies `LEDGER_ENTRY_BATCH_COMMIT_SIZE` entries then exits. This means that, especially for large buckets, `BucketApplicator::advance` must be called many times before the Bucket finishes applying. The issue is this code only calls `BucketApplicator::advance` a single time before moving on to the next bucket.

If you look at the old `ApplyBucketsWork`, we maintained `mFirstBucketApplicator` and `mSecondBucketApplicator` pointers to persist Applicators across calls to `doWork`. We only move on to the next bucket when `*mFirstBucketApplicator` is false (note that this is pointer dereference, not checking if the pointer itself is null), indicating the applicator has reached EOF. You need to implement similar logic, where you maintain an applicator pointer and only advance to the next bucket when the applicator is false. Currently you check if `applicator` is true once then call apply, but you always advance to the next bucket unconditional, even if after the first call to `advance` `applicator` is still `true`.

2024-05-17 00:45 UTC, SirTyson approved these changes
Overall looks good to me! Just a few nit pics. There's still some complexity involving `mLevel` and `isCurr` I'd like to see get factored out, but unfortunately it looks like this may be required given how we check invariants :(

2024-06-03 16:45 UTC, SirTyson commented
r+ ba9f43f939606d74752e1910fefd3e4fc76f0cec

2024-06-04 17:31 UTC, SirTyson commented
Trying again

r+ 545b721eb3a7ef518bd21a89b2e83d02d039632f

2024-06-04 19:58 UTC, graydon commented
@latobarita: retry

2024-06-04 22:38 UTC, graydon commented
r+ 545b721

2024-06-05 18:38 UTC, ThomasBrady commented
@latobarita: retry

2024-07-01 19:26 UTC, merged