Parallel txset nomination
stellar/stellar-core pull request #4486
Opened 2024-09-25 17:30 UTC by dmkozh

WIP draft

2025-02-25 00:29 UTC, sisuresh commented on src/main/Config.cpp
> +    SOROBAN_PHASE_STAGE_COUNT = 1;
I think you've mentioned this setting should be dynamically determined by the contents of the tx queue instead of hardcoded. What's the plan wrt that?

2025-02-25 21:17 UTC, dmkozh commented on src/herder/ParallelTxSetBuilder.cpp
> +                      bool& packed)
That works as well, I just wanted to avoid copying the vector unnecessarily.

2025-02-25 21:17 UTC, dmkozh commented on src/herder/ParallelTxSetBuilder.cpp
> +        // exceed the theorethical limit of instructions per stage.
Fixed

2025-02-25 21:19 UTC, dmkozh commented on src/main/Config.cpp
> +    SOROBAN_PHASE_STAGE_COUNT = 1;
I think that would be a separate PR. But I think we could make a few tx sets in parallel and use the one with the smallest amount of stages that provides roughly the same utilization.

2025-04-24 06:17 UTC, graydon requested changes
Nice! A couple suggested comments and a few requests for either clarification of the algorithm's assumptions, either through commentary or some additional data-model refinement or something. Unsure.

2025-04-24 19:41 UTC, dmkozh commented on src/herder/ParallelTxSetBuilder.cpp
> +    }
Bin-packing is actually in an 'invalid' state only for a brief period of time (until we've assigned the clusters). But the function indeed has done too much; I broke it down further and now I think the invariant should be pretty clear. I don't think `mBinPacking` needs to be optional as it's never in and undefined state (it's just sometimes in 'partially commited' state, which we kind of need to have as we have two members that are updated at once).
I've added the optional return values though.

2025-04-24 19:41 UTC, dmkozh commented on src/herder/ParallelTxSetBuilder.cpp
> +        return newClusters;
I've factored this into a separate function `inPlaceBinPacking` and updated the comment. Basically we remove the clusters that are no longer needed, then try packing the new cluster, then revert the changes in case if we couldn't pack it, i.e. the stage remains unchanged. 

> Or maybe we want to hold on to the old bin packing in case a new full bin packing isn't even possible? I feel a bit uncertain.

Yes, this function should only be effectively mutating in case if in-place packing is possible. If it's not possible, then we shouldn't change anything, as we're not guaranteed to be able to add the cluster at all even with the full bin packing (in other words we only 'commit' valid states into Stage).

2025-04-24 19:41 UTC, dmkozh commented on src/herder/ParallelTxSetBuilder.cpp
> +        }
Yeah, this is the de-facto logic and `mBinId` is really always defined when it's necessary. But making it `optional` is cheap and it does make the invariants more clear and provides a bit of runtime safety.

2025-04-25 04:01 UTC, graydon requested changes
Handful of additional nits, but as far as I can understand it, looks good!

The txqueue remains somewhat mysterious to me but it looks like you're mostly just generalizing existing code to work over `variant<TxFrameList,TxStageFrameList>`, which seems harmless enough.

Also I did not mention this everywhere it's relevant, but I am a little nervous about all the unchecked vector indexing with `[]` -- everything I could eyeball looks in-bounds, but in general if you use `.at()` you get check-and-throw rather than UB when there's an out-of-bounds bug. I know it's a lot of call sites to change (and there are lots of `[]` index operations elsewhere in the code already) but I have a general preference for `.at()` if you're willing to indulge it.

2025-04-25 04:37 UTC, graydon commented on src/herder/TxSetFrame.cpp
> +                    {
Actually: I spent a little time poking at this and am not sure I really like it? The thing about `if constexpr` is that if it evaluates to false, the compiler just erases the block. It doesn't tell you and doesn't even typecheck it or anything. So if your `is_same_v` is describing a condition that never holds, for example a case that's not a member of the variant, you'll never know. It'll compile "as if" you covered all cases, but actually you did not. I guess that's what the final assert is for -- something like exhaustiveness checking -- but it makes me even more interested in having that final arm be a `static_assert(false)`, to catch it at compile time.

2025-04-25 15:14 UTC, dmkozh commented on src/herder/ParallelTxSetBuilder.cpp
> +    releaseAssert(hadTxNotFittingLane.size() == 1);
There is only a single fee 'lane' for Soroban, i.e. everyone is surge-priced (or not surge-priced) at once. This vector basically indicates per-lane surge pricing (had tx that didn't fit => trigger surge pricing). I've added a comment.

2025-04-25 16:02 UTC, dmkozh commented
> Also I did not mention this everywhere it's relevant, but I am a little nervous about all the unchecked vector indexing with [] -- everything I could eyeball looks in-bounds, but in general if you use .at() you get check-and-throw rather than UB when there's an out-of-bounds bug. I know it's a lot of call sites to change (and there are lots of [] index operations elsewhere in the code already) but I have a general preference for .at() if you're willing to indulge it.

This is not too hard to change, but there is some performance cost (~4%) and I'm not sure if this provides much additional protection vs asan and debug builds. This code path is also not a part of consensus and it can't result in nominating a bad tx set, as every node would validate it.

2025-04-25 18:10 UTC, graydon approved these changes

2025-04-25 18:27 UTC, graydon submitted a review, later dismissed

2025-04-25 20:02 UTC, graydon approved these changes

2025-04-25 22:34 UTC, merged